### ISSUE TITLE
Trigger Nuget build

### ISSUE THREAD

**Issue by techtim** [MatthewKing/DeviceId#21]
The last version is 4 months old, please update Nuget with the latest commits for OSX

**Comment by MatthewKing** [comment]
Hi Tim,

I was waiting for some feedback from you (or another Mac user) on [this issue](https://github.com/MatthewKing/DeviceId/pull/16) as I'm not too familiar with OS X and I wasn't sure whether the IOPlatformSerialNumber would be better as a SystemUUID rather than a ProcessorId. Would really appreciate the expertise of a Mac user regarding the categorization of this component. Cheers!

**Comment by techtim** [comment]
Sorry, I didn't see your question in the PR. 
I didn't find the way to get exactly Processor Id on OSX, looks like there is none, so relying on Apple ID I found the most suitable to uniquely identify a mac, because people tend to use CPU id as the most unique variable available IOPlatformSerialNumber fits good. If use it for SystemUUID it will duplicate  ProcessorId or ProcessorId will be empty

**Comment by MatthewKing** [comment]
Thanks mate, the feedback is appreciated. I've decided to add it to the OSInstallationID component, as it's technically not a processor ID. Hope that's alright for your use case. I'm triggering a build now, so it should show up on NuGet soon. Cheers!
