### ISSUE TITLE
After Update nothing works.

### ISSUE THREAD

**Issue by Pinguu-dev** [MatthewKing/DeviceId#33]
After 6.0.0 update you change much, readme is outdated.
.AddProcessorId.. does not exist anymore.

What you change?

**Comment by MatthewKing** [comment]
It's in the readme.

**Comment by EinfachMaxYT** [comment]
OnWindows does not exist

**Comment by EinfachMaxYT** [comment]
![image](https://user-images.githubusercontent.com/72171280/129487099-61898e8e-cfe5-4e79-af10-196421561756.png)

**Comment by MatthewKing** [comment]
As of version 6, the packages have been split up so that users can pick-and-choose what they need, without having to pull down unnecessary references that they won't use. So if you want to use `.AddProcessorId` you also need to add the `DeviceId.Windows.Wmi` package (or the `DeviceId.Windows.Mmi` package).
