### ISSUE TITLE
Release documentation

### ISSUE THREAD

**Issue by AlexSchuetz** [MatthewKing/DeviceId#35]
Hi,
I tried to upgrade from 5.2.0 to 6.0.0.

Unfortunately the API changed and I don't know if this would affect my program, by returning different DeviceIds for the same machine/configuration or if I need to do some migration.

For example the AddOSInstallationID-method, that I use is gone.

It would be great if you document your releases and possibly breaking changes.

**Comment by MatthewKing** [comment]
Hi Alex.

Fair call. I'll add some migration notes when I get some time. v6 definitely has some breaking changes, but v5 was still a fine release and if you don't want to deal with the changes it's completely fine to stay on v5 for most apps.

For you (and anyone else reading this), the doco does mention that if you've just been using the default formatter, you'll now have to specify that you want the `DefaultV5` formatter, as the default has changed.

As for OSInstallationID: It has been removed because it was a bad naming convention that didn't make sense across 3 different platforms. You can reproduce it on Windows with something like: `builder.OnWindows(x => x.AddRegistryValue("OSInstallationID", @"HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Cryptography", "MachineGuid"));`

Hope this helps
